# Generated by Django 5.1.1 on 2024-09-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_commentres"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentres",
            old_name="receipe",
            new_name="recipe",
        ),
    ]
