# Generated by Django 5.1.1 on 2024-09-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_receipe_commentres_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentres",
            old_name="recipe",
            new_name="receipe",
        ),
    ]
