# Generated by Django 5.1.1 on 2024-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_receipe_commentres_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="blogs/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(blank=True, upload_to="recipes/%Y/%m/%d/"),
        ),
    ]
