# Generated by Django 5.1.1 on 2024-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_post_photo_recipe_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/blogs/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/recipes/%Y/%m/%d/"),
        ),
    ]
