# Generated by Django 5.1.1 on 2024-10-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_bookmarkpost_bookmarkrecipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="blogs/%Y/%m/%d/"),
        ),
    ]
