# Generated by Django 5.1.1 on 2024-10-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(blank=True, upload_to="recipes/%Y/%m/%d/"),
        ),
    ]
